### ISSUE TITLE
create build graph for xtu-analyze

### ISSUE THREAD

**Issue by dkrupp** [dkrupp/clang#12]
Create a script
xtu-build-graph.py <-b build.json> <-c cfg.txt> <-d definedFns.txt> <-o build-graph.json> <-x no-xtu-list.json>

the build graph will be used by the new xtu-analyize.py to optimally schedule clang 2nd phase analysis threads.

The format of the build-graph.json shall be the following

[{1,2},{5,3}]

which means that build command "2" must be run after build command "1".
The numbers mean the order of the build command in the input build database (build.json).

The build graph must be free of circles (otherwise the scheduler will get into deadlock).

**Comment by dkrupp** [comment]
json format was incorrect. now it is fixed.

**Comment by gerazo** [comment]
@szepet your indexes in your output file do not refer to the order in the original json. They number only the build commands which refer to source files. I think it can be error prone, especially if patterns do not match (which I've fixed here https://github.com/dkrupp/clang/commit/08bed0696473a60472f3911fdd5fb4decea2790c   still we have the problem).

**Comment by gerazo** [comment]
I've fixed the above error. I think this can be closed now. Your script is working.
