### ISSUE TITLE
xtu-analyze.py schedule clang execution accoding to the build graph.json

### ISSUE THREAD

**Issue by dkrupp** [dkrupp/clang#17]

**Comment by dkrupp** [comment]
by default, clang on 1 thread

**Comment by gerazo** [comment]
Done in https://github.com/dkrupp/clang/commit/487419f2e2dee3283cca44d3b73c3bef0bdaed11

**Comment by gerazo** [comment]
There was a small problem left. Indexing was counting only sources in build graph while analyze script ws indexing all buildlog entries. Now analyze script counts only source action: https://github.com/dkrupp/clang/commit/41d1290087be0b3afe5957be4e852c0d11b4674a
With this all scripts work together fine.
