### ISSUE TITLE
explain why analyzed basic blocks is drastically larger in the non-xtu case comapared to the xtu

### ISSUE THREAD

**Issue by dkrupp** [dkrupp/clang#20]
options
-simplify the exploded graph output so that only function calls, branching is shown
-generate bug reports whenever the analysis path is cut, then report this as a bug that can be imported into codechecker

**Comment by Xazax-hun** [comment]
While we already know that the drastic difference was the result of analysing headers, implementing these tools could be still helpful for justifying cross TU functionality.
