### ISSUE TITLE
fix plist output support

### ISSUE THREAD

**Issue by gyorb** [dkrupp/clang#21]
fix plist output support in analyze-cc

**Comment by gerazo** [comment]
Quick fix is here: https://github.com/dkrupp/clang/commit/8bcad37c5861e64791888fae7b3a742772efbcaf
Still ongoing TODO: commit back into https://github.com/rizsotto/scan-build as the problem is still there.

**Comment by gerazo** [comment]
Here is the ongoing pull request back into scan-build: https://github.com/rizsotto/scan-build/pull/78

**Comment by gerazo** [comment]
The pull request was accepted. The new version of scan-build is about to be released back into clang here: https://reviews.llvm.org/D26390
After this release, this fix will also be put into the master branch of scan-build.
