### ISSUE TITLE
new xtu script arguments

### ISSUE THREAD

**Issue by gyorb** [dkrupp/clang#25]
* the user should be able to set if xtu analysis is started or not
* with the upcoming coverage support in clang it would be nice to be able to enable the generation of coverage information
* gcov files should be exported to a separate directory for each translation unit (like xtudir/tu1, xtudir/tu2 etc) and the gcov files from these directories should be merged using the python script

**Comment by Xazax-hun** [comment]
For coverage support see https://github.com/dkrupp/clang/commit/6046067b95552f39f312c00eb0434f09560fb928

Test files and the gcov merger python script contains useful information how to use feature.

**Comment by gerazo** [comment]
Skipping XTU is now available: https://github.com/dkrupp/clang/commit/702ffa63d78291f044e0c2187703d8606783bfff  the rest is coming

**Comment by gerazo** [comment]
record-coverage option is introduced here: https://github.com/dkrupp/clang/commit/d9c225c35ef0b0d0c079863284337158205e85d2
It uses XTU out dir as the destionation

**Comment by Xazax-hun** [comment]
The gcov files should be exported to a separate directory for each translation unit (like xtudir/tu1, xtudir/tu2 etc) and the gcov files from these directories should be merged using the python script I introduced.

**Comment by gerazo** [comment]
the merging is ready as well: https://github.com/dkrupp/clang/commit/bade54674c12fbb09a823936a79a289a12646253
