### ISSUE TITLE
creat script on ELTE server to reanalyze open source projects

### ISSUE THREAD

**Issue by dkrupp** [dkrupp/clang#47]
-vim
-ffmpeg
-tmux
-memcached
-xerces

-public codechecker port with baseline, xtu analysis for each project
-run nightly
-timestamp run names
-put additional info into a html file: analysis time, passed files, failed files

**Comment by gerazo** [comment]
The scripts are at http://mainstream.inf.elte.hu/gerazo/xtu-scripts
