### ISSUE TITLE
create separate analysis page for tmux, memcached

### ISSUE THREAD

**Issue by dkrupp** [dkrupp/clang#49]
create an analysis page on the wiki for tmux and memcached
with the true/false positives on the wiki separately for tmux and memchached
similar to this page

https://github.com/dkrupp/clang/wiki/FFMpeg-XTU-Analysis

**Comment by gamesh411** [comment]
Made some modifications on the build script that I use to create the xtu-analyzer reports (namely left out autogen and configure steps from the -b cmdline argument). Not even autogenerated c files cause fails anymore. I will be able to check this evening, whether the results are "sane" or not.

**Comment by gamesh411** [comment]
Updated memcached wiki with new analysis information. This seems much more promising than the last one. Found a very specific bug, that could only be found via ctu-analysis.
