### ISSUE TITLE
error: external function 'Curl_closesocket' declared with incompatible types

### ISSUE THREAD

**Issue by dkrupp** [dkrupp/clang#65]

**Comment by gerazo** [comment]
In curl/src/tool_main.c, 7 errors, all are same:

analyze: INFO: Importing function _Z16Curl_closesocketP11connectdatai@x86_64 from /mnt/storage/gerazo/clang_asan/curl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/c
url/lib/connect.c.ast
analyze: INFO: /mnt/storage/gerazo/clang_asan/curl/lib/connect.c:1289:5: error: external function 'Curl_closesocket' declared with incompatible types in different translation units ('int (struct connectdata *, curl_socket_t)' (aka 'int (struct connectdata *, int)') vs. 'int (struct connectdata *, curl_socket_t)' (aka 'int (struct connectdata *, int)'))
analyze: INFO: int Curl_closesocket(struct connectdata *conn,
analyze: INFO:     ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/curl/lib/connect.h:77:5: note: declared here with type 'int (struct connectdata *, curl_socket_t)' (aka 'int (struct connectdata *, int)')
analyze: INFO: int Curl_closesocket(struct connectdata *conn, curl_socket_t sock);
analyze: INFO:     ^

analyze: INFO: Importing function _Z9Curl_openPP9Curl_easy@x86_64 from /mnt/storage/gerazo/clang_asan/curl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/curl/lib/url.c.ast
analyze: INFO: /mnt/storage/gerazo/clang_asan/curl/lib/url.c:620:10: error: external function 'Curl_open' declared with incompatible types in different translation units ('CURLcode (struct Curl_easy **)' vs. 'CURLcode (struct Curl_easy **)')
analyze: INFO: CURLcode Curl_open(struct Curl_easy **curl)
analyze: INFO:          ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/curl/lib/url.h:31:10: note: declared here with type 'CURLcode (struct Curl_easy **)'
analyze: INFO: CURLcode Curl_open(struct Curl_easy **curl);
analyze: INFO:          ^

analyze: INFO: Importing function _Z13Curl_initinfoP9Curl_easy@x86_64 from /mnt/storage/gerazo/clang_asan/curl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/curl/lib/getinfo.c.ast
analyze: INFO: /mnt/storage/gerazo/clang_asan/curl/lib/getinfo.c:45:10: error: external function 'Curl_initinfo' declared with incompatible types in different translation units ('CURLcode (struct Curl_easy *)' vs. 'CURLcode (struct Curl_easy *)')
analyze: INFO: CURLcode Curl_initinfo(struct Curl_easy *data)
analyze: INFO:          ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/curl/lib/getinfo.h:25:10: note: declared here with type 'CURLcode (struct Curl_easy *)'
analyze: INFO: CURLcode Curl_initinfo(struct Curl_easy *data);
analyze: INFO:          ^

analyze: INFO: Importing function _Z22Curl_ssl_free_certinfoP9Curl_easy@x86_64 from /mnt/storage/gerazo/clang_asan/curl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/curl/lib/vtls/vtls.c.ast
analyze: INFO: /mnt/storage/gerazo/clang_asan/curl/lib/vtls/vtls.c:611:6: error: external function 'Curl_ssl_free_certinfo' declared with incompatible types in different translation units ('void (struct Curl_easy *)' vs. 'void (struct Curl_easy *)')
analyze: INFO: void Curl_ssl_free_certinfo(struct Curl_easy *data)
analyze: INFO:      ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/curl/lib/vtls/vtls.h:100:6: note: declared here with type 'void (struct Curl_easy *)'
analyze: INFO: void Curl_ssl_free_certinfo(struct Curl_easy *data);
analyze: INFO:      ^

analyze: INFO: Importing function _Z10Curl_closeP9Curl_easy@x86_64 from /mnt/storage/gerazo/clang_asan/curl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/curl/lib/url.c.ast
analyze: INFO: /mnt/storage/gerazo/clang_asan/curl/lib/url.c:390:10: error: external function 'Curl_close' declared with incompatible types in different translation units ('CURLcode (struct Curl_easy *)' vs. 'CURLcode (struct Curl_easy *)')
analyze: INFO: CURLcode Curl_close(struct Curl_easy *data)
analyze: INFO:          ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/curl/lib/url.h:37:10: note: declared here with type 'CURLcode (struct Curl_easy *)'
analyze: INFO: CURLcode Curl_close(struct Curl_easy *data); /* opposite of curl_open() */
analyze: INFO:          ^
analyze: INFO: In file included from /mnt/storage/gerazo/clang_asan/curl/lib/url.c:74:
analyze: INFO: /mnt/storage/gerazo/clang_asan/curl/lib/vtls/vtls.h:100:6: error: external function 'Curl_ssl_free_certinfo' declared with incompatible types in different translation units ('void (struct Curl_easy *)' vs. 'void (struct Curl_easy *)')
analyze: INFO: void Curl_ssl_free_certinfo(struct Curl_easy *data);
analyze: INFO:      ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/curl/lib/vtls/vtls.h:100:6: note: declared here with type 'void (struct Curl_easy *)'
analyze: INFO: void Curl_ssl_free_certinfo(struct Curl_easy *data);
analyze: INFO:      ^
analyze: INFO: In file included from /mnt/storage/gerazo/clang_asan/curl/lib/url.c:74:
analyze: INFO: /mnt/storage/gerazo/clang_asan/curl/lib/vtls/vtls.h:100:6: error: external function 'Curl_ssl_free_certinfo' declared with incompatible types in different translation units ('void (struct Curl_easy *)' vs. 'void (struct Curl_easy *)')
analyze: INFO: void Curl_ssl_free_certinfo(struct Curl_easy *data);
analyze: INFO:      ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/curl/lib/vtls/vtls.c:611:6: note: declared here with type 'void (struct Curl_easy *)'
analyze: INFO: void Curl_ssl_free_certinfo(struct Curl_easy *data)
analyze: INFO:      ^

**Comment by dkrupp** [comment]
create a minimal example that crashes the same way.
add an ASSERT when the first type import fails

**Comment by gerazo** [comment]
55 files failing in postgresql has this. Important bug to fix.

**Comment by gerazo** [comment]
Although curl has zero from this error now, openssl and postgresql still has a lot. (The 72 of openssl went down to 39)
