### ISSUE TITLE
astimporter error - external function declared with incompatible types in different translation unit

### ISSUE THREAD

**Issue by dkrupp** [dkrupp/clang#67]
error while analyzing ac3enc.c in ffmpeg.

analyze: INFO: /ssd/ednikru/ctu/tests/FFmpeg/libavcodec/eac3enc.c:68:6: error: external function 'ff_eac3_get_frame_exp_strategy' declared with incompatible types in different translation units ('void (AC3EncodeContext *)' (aka 'void (struct AC3EncodeContext *)') vs. 'void (AC3EncodeContext *)' (aka 'void (struct AC3EncodeContext *)'))

ednikru@md-mtas2:~/ssd/ctu/tests/FFmpeg$ cat ./.xtu-out/fails/ac3enc.c_d9d2d42c-62ff-430c-ae4c-2f9cc13179b2.out 
/ssd/ednikru/ctu/clang_github-fork/clang/tools/scan-build-py/bin/analyze-cc -I/ssd/ednikru/ctu/tests/FFmpeg -I/ssd/ednikru/ctu/tests/FFmpeg -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DZLIB_CONST -DHAVE_AV_CONFIG_H -std=c99 -fomit-frame-pointer -pthread -g -Wdeclaration-after-statement -Wall -Wdisabled-optimization -Wpointer-arith -Wredundant-decls -Wwrite-strings -Wtype-limits -Wundef -Wmissing-prototypes -Wno-pointer-to-int-cast -Wstrict-prototypes -Wempty-body -Wno-parentheses -Wno-switch -Wno-format-zero-length -Wno-pointer-sign -O3 -fno-math-errno -fno-signed-zeros -fno-tree-vectorize -Werror=format-security -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=return-type -Werror=vla -Wformat -Wno-maybe-uninitialized -MMD -MF libavcodec/ac3enc.d -MT libavcodec/ac3enc.o -c -o /ssd/ednikru/ctu/tests/FFmpeg/libavcodec/ac3enc.o /ssd/ednikru/ctu/tests/FFmpeg/libavcodec/ac3enc.c
analyze: INFO: execute compiler: gcc -I/ssd/ednikru/ctu/tests/FFmpeg -I/ssd/ednikru/ctu/tests/FFmpeg -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DZLIB_CONST -DHAVE_AV_CONFIG_H -std=c99 -fomit-frame-pointer -pthread -g -Wdeclaration-after-statement -Wall -Wdisabled-optimization -Wpointer-arith -Wredundant-decls -Wwrite-strings -Wtype-limits -Wundef -Wmissing-prototypes -Wno-pointer-to-int-cast -Wstrict-prototypes -Wempty-body -Wno-parentheses -Wno-switch -Wno-format-zero-length -Wno-pointer-sign -O3 -fno-math-errno -fno-signed-zeros -fno-tree-vectorize -Werror=format-security -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=return-type -Werror=vla -Wformat -Wno-maybe-uninitialized -MMD -MF libavcodec/ac3enc.d -MT libavcodec/ac3enc.o -c -o /ssd/ednikru/ctu/tests/FFmpeg/libavcodec/ac3enc.o /ssd/ednikru/ctu/tests/FFmpeg/libavcodec/ac3enc.c
analyze: INFO: Importing function _Z6av_logPviPKcz@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/log.c.ast
analyze: INFO: _ZL23ac3_output_frame_headerP16AC3EncodeContext@x86_64 has_work_wl not_exhausted no_block_aborted
analyze: INFO: Importing function _Z16av_crc_get_table7AVCRCId@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/crc.c.ast
analyze: INFO: Importing function _Z6av_crcPKjjPKhm@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/crc.c.ast
analyze: INFO: _Z19ff_ac3_output_frameP16AC3EncodeContextPh@x86_64 empty_wl block_exhausted no_block_aborted
analyze: INFO: _ZL18output_audio_blockP16AC3EncodeContexti@x86_64 has_work_wl block_exhausted no_block_aborted
analyze: INFO: _Z25ff_ac3_quantize_mantissasP16AC3EncodeContext@x86_64 has_work_wl block_exhausted no_block_aborted
analyze: INFO: _Z22ff_ac3_group_exponentsP16AC3EncodeContext@x86_64 has_work_wl block_exhausted no_block_aborted
analyze: INFO: Importing function _Z25ff_ac3_bit_alloc_calc_psdPaiiPsS0_@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavcodec/ac3.c.ast
analyze: INFO: Importing function _Z26ff_ac3_bit_alloc_calc_maskP21AC3BitAllocParametersPsiiiiiiPhS2_S2_S1_@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavcodec/ac3.c.ast
analyze: INFO: _Z29ff_ac3_compute_bit_allocationP16AC3EncodeContext@x86_64 empty_wl not_exhausted no_block_aborted
analyze: INFO: _ZL16count_frame_bitsP16AC3EncodeContext@x86_64 has_work_wl block_exhausted no_block_aborted
analyze: INFO: Importing function _Z30ff_eac3_get_frame_exp_strategyP16AC3EncodeContext@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavcodec/eac3enc.c.ast
analyze: INFO: /ssd/ednikru/ctu/tests/FFmpeg/libavcodec/eac3enc.c:68:6: error: external function 'ff_eac3_get_frame_exp_strategy' declared with incompatible types in different translation units ('void (AC3EncodeContext *)' (aka 'void (struct AC3EncodeContext *)') vs. 'void (AC3EncodeContext *)' (aka 'void (struct AC3EncodeContext *)'))
analyze: INFO: void ff_eac3_get_frame_exp_strategy(AC3EncodeContext *s)
analyze: INFO:      ^
analyze: INFO: /ssd/ednikru/ctu/tests/FFmpeg/libavcodec/eac3enc.h:40:6: note: declared here with type 'void (AC3EncodeContext *)' (aka 'void (struct AC3EncodeContext *)')
analyze: INFO: void ff_eac3_get_frame_exp_strategy(AC3EncodeContext *s);
analyze: INFO:      ^
analyze: INFO: _Z24ff_ac3_process_exponentsP16AC3EncodeContext@x86_64 empty_wl not_exhausted no_block_aborted
analyze: INFO: _ZL23encode_exponents_blk_chPhiii@x86_64 empty_wl block_exhausted no_block_aborted
analyze: INFO: _Z24ff_ac3_apply_rematrixingP16AC3EncodeContext@x86_64 has_work_wl block_exhausted no_block_aborted
analyze: INFO: _Z32ff_ac3_compute_coupling_strategyP16AC3EncodeContext@x86_64 empty_wl block_exhausted no_block_aborted
analyze: INFO: _Z24ff_ac3_adjust_frame_sizeP16AC3EncodeContext@x86_64 empty_wl block_exhausted no_block_aborted
analyze: INFO: Importing function _Z16ff_audiodsp_initP15AudioDSPContext@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavcodec/audiodsp.c.ast
analyze: INFO: Importing function _Z20ff_audiodsp_init_x86P15AudioDSPContext@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavcodec/x86/audiodsp_init.c.ast
analyze: INFO: Importing function _Z16av_get_cpu_flagsv@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/cpu.c.ast
analyze: INFO: Importing function _Z20ff_get_cpu_flags_x86v@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/x86/cpu.c.ast
analyze: INFO: Importing function _Z14ff_me_cmp_initP12MECmpContextP14AVCodecContext@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavcodec/me_cmp.c.ast
analyze: INFO: Importing function _Z19ff_dsputil_init_dwtP12MECmpContext@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavcodec/snow_dwt.c.ast
analyze: INFO: Importing function _Z18ff_me_cmp_init_x86P12MECmpContextP14AVCodecContext@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavcodec/x86/me_cmp_init.c.ast
analyze: INFO: Importing function _Z14ff_ac3dsp_initP13AC3DSPContexti@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavcodec/ac3dsp.c.ast
analyze: INFO: Importing function _Z18ff_ac3dsp_init_x86P13AC3DSPContexti@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavcodec/x86/ac3dsp_init.c.ast
analyze: INFO: _Z18ff_ac3_encode_initP14AVCodecContext@x86_64 has_work_wl not_exhausted no_block_aborted
analyze: INFO: Importing function _Z8av_freepPv@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/mem.c.ast
analyze: INFO: _Z19ff_ac3_encode_closeP14AVCodecContext@x86_64 empty_wl block_exhausted no_block_aborted
analyze: INFO: Importing function _Z9av_mallocm@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/mem.c.ast
analyze: INFO: Importing function _Z10av_malloczm@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/mem.c.ast
analyze: INFO: _ZL16allocate_buffersP16AC3EncodeContext@x86_64 empty_wl block_exhausted no_block_aborted
analyze: INFO: _ZL16validate_optionsP16AC3EncodeContext@x86_64 has_work_wl block_exhausted no_block_aborted
analyze: INFO: _Z24ff_ac3_validate_metadataP16AC3EncodeContext@x86_64 has_work_wl not_exhausted no_block_aborted
analyze: INFO: _ZL18validate_mix_levelPvPKcPfPKfiiiPi@x86_64 empty_wl not_exhausted no_block_aborted
analyze: INFO: /ssd/ednikru/ctu/tests/FFmpeg/libavcodec/ac3enc.c:288:17: warning: Array access (from variable 'flags') results in a null pointer dereference
analyze: INFO:             if (flags[bnd]) {
analyze: INFO:                 ^~~~~~~~~~
analyze: INFO: ===-------------------------------------------------------------------------===
analyze: INFO:                          Miscellaneous Ungrouped Timers
analyze: INFO: ===-------------------------------------------------------------------------===
analyze: INFO: 
analyze: INFO:    ---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
analyze: INFO:   266.0809 (100.0%)   0.7074 (100.0%)  266.7884 (100.0%)  268.6547 (100.0%)  Analyzer Total Time
analyze: INFO:   266.0809 (100.0%)   0.7074 (100.0%)  266.7884 (100.0%)  268.6547 (100.0%)  Total
analyze: INFO: 
analyze: INFO: ===-------------------------------------------------------------------------===
analyze: INFO:                           ... Statistics Collected ...
analyze: INFO: ===-------------------------------------------------------------------------===
analyze: INFO: 
analyze: INFO:    2717 ASTContext       - The # of getXTUDefinition function called
analyze: INFO:      96 ASTContext       - The # of getXTUDefinition successfully return the requested function's body
analyze: INFO:    2621 ASTContext       - The # of getXTUDefinition called but the function is not in other TU
analyze: INFO:     128 AnalysisConsumer - The maximum number of basic blocks in a function.
analyze: INFO:    1352 AnalysisConsumer - The # of basic blocks in the analyzed functions.
analyze: INFO:     148 AnalysisConsumer - The # of functions at top level.
analyze: INFO:      18 AnalysisConsumer - The # of functions and blocks analyzed (as top level with inlining turned on).
analyze: INFO:      72 AnalysisConsumer - The % of reachable basic blocks.
analyze: INFO:      12 BugReporter      - The maximum number of bug reports in the same equivalence class
analyze: INFO:      12 BugReporter      - The maximum number of bug reports in the same equivalence class where at least one report is valid (not suppressed)
analyze: INFO:     221 CoreEngine       - The # of paths explored by the analyzer.
analyze: INFO:       9 CoreEngine       - The # of times we reached the max number of steps.
analyze: INFO: 1777198 CoreEngine       - The # of steps executed.
analyze: INFO:    7837 ExprEngine       - The # of times we inlined a call
analyze: INFO:    9885 ExprEngine       - The # of aborted paths due to reaching the maximum block count in a top level function
analyze: INFO:    1255 ExprEngine       - The # of times we reached inline count maximum
analyze: INFO:  316055 ExprEngine       - The # of times RemoveDeadBindings is called
analyze: INFO:      22 ExprEngine       - The # of times we re-evaluated a call without inlining
analyze: INFO: 
analyze: INFO: 1 warning and 1 error generated.

**Comment by Xazax-hun** [comment]
Seems to be a bug in ffmpeg.

**Comment by dkrupp** [comment]
The report was issued to ffmpeg : https://trac.ffmpeg.org/ticket/6117
