### ISSUE TITLE
astimporter assert - Assertion `StartColNo <= EndColNo && "Invalid range!"' failed

### ISSUE THREAD

**Issue by dkrupp** [dkrupp/clang#68]
ffmpeg analyzing avfiltergraph.c

/ssd/ednikru/ctu/clang_github-fork/clang/tools/scan-build-py/bin/analyze-cc I/ssd/ednikru/ctu/tests/FFmpeg -I/ssd/ednikru/ctu/tests/FFmpeg -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DZLIB_CONST -DHAVE_AV_CONFIG_H -std=c99 -fomit-frame-pointer -pthread -g -Wdeclaration-after-statement -Wall -Wdisabled-optimization -Wpointer-arith -Wredundant-decls -Wwrite-strings -Wtype-limits -Wundef -Wmissing-prototypes -Wno-pointer-to-int-cast -Wstrict-prototypes -Wempty-body -Wno-parentheses -Wno-switch -Wno-format-zero-length -Wno-pointer-sign -O3 -fno-math-errno -fno-signed-zeros -fno-tree-vectorize -Werror=format-security -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=return-type -Werror=vla -Wformat -Wno-maybe-uninitialized -MMD -MF libavfilter/avfiltergraph.d -MT libavfilter/avfiltergraph.o -c -o /ssd/ednikru/ctu/tests/FFmpeg/libavfilter/avfiltergraph.o /ssd/ednikru/ctu/tests/FFmpeg/libavfilter/avfiltergraph.c
analyze: INFO: execute compiler: gcc -I/ssd/ednikru/ctu/tests/FFmpeg -I/ssd/ednikru/ctu/tests/FFmpeg -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DZLIB_CONST -DHAVE_AV_CONFIG_H -std=c99 -fomit-frame-pointer -pthread -g -Wdeclaration-after-statement -Wall -Wdisabled-optimization -Wpointer-arith -Wredundant-decls -Wwrite-strings -Wtype-limits -Wundef -Wmissing-prototypes -Wno-pointer-to-int-cast -Wstrict-prototypes -Wempty-body -Wno-parentheses -Wno-switch -Wno-format-zero-length -Wno-pointer-sign -O3 -fno-math-errno -fno-signed-zeros -fno-tree-vectorize -Werror=format-security -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=return-type -Werror=vla -Wformat -Wno-maybe-uninitialized -MMD -MF libavfilter/avfiltergraph.d -MT libavfilter/avfiltergraph.o -c -o /ssd/ednikru/ctu/tests/FFmpeg/libavfilter/avfiltergraph.o /ssd/ednikru/ctu/tests/FFmpeg/libavfilter/avfiltergraph.c
analyze: INFO: _Z29ff_filter_graph_remove_filterP13AVFilterGraphP15AVFilterContext@x86_64 empty_wl block_exhausted no_block_aborted
analyze: INFO: Importing function _Z6av_logPviPKcz@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/log.c.ast
analyze: INFO: _Z29ff_avfilter_graph_update_heapP13AVFilterGraphP12AVFilterLink@x86_64 empty_wl not_exhausted no_block_aborted
analyze: INFO: Importing function _Z16ff_request_frameP12AVFilterLink@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavfilter/avfilter.c.ast
analyze: INFO: Importing function _Z28av_get_channel_layout_stringPciim@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/channel_layout.c.ast
analyze: INFO: Importing function _Z25av_bprint_init_for_bufferP8AVBPrintPcj@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/bprint.c.ast
analyze: INFO: Importing function _Z33av_get_channel_layout_nb_channelsm@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/channel_layout.c.ast
analyze: INFO: Importing function _Z26ff_request_frame_to_filterP12AVFilterLink@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavfilter/avfilter.c.ast
analyze: INFO: Importing function _Z31ff_avfilter_link_set_out_statusP12AVFilterLinkil@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavfilter/avfilter.c.ast
analyze: INFO: Importing function _Z12av_rescale_ql10AVRationalS_@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/mathematics.c.ast
analyze: INFO: Importing function _Z20av_frame_get_pkt_posPK7AVFrame@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/frame.c.ast
analyze: INFO: Importing function _Z12av_expr_evalP6AVExprPKdPv@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/eval.c.ast
analyze: INFO: Importing function _Z15ff_filter_frameP12AVFilterLinkP7AVFrame@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavfilter/avfilter.c.ast
analyze: INFO: Importing function _Z8av_freepPv@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/mem.c.ast
analyze: INFO: Importing function _Z20av_frame_is_writableP7AVFrame@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/frame.c.ast
analyze: INFO: Importing function _Z21av_buffer_is_writablePK11AVBufferRef@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/buffer.c.ast
analyze: INFO: Importing function _Z13av_frame_freePP7AVFrame@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/frame.c.ast
analyze: INFO: Importing function _Z14av_frame_unrefP7AVFrame@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/frame.c.ast
analyze: INFO: Importing function _Z19ff_get_audio_bufferP12AVFilterLinki@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavfilter/audio.c.ast
analyze: INFO: Importing function _Z19av_frame_copy_propsP7AVFramePKS_@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/frame.c.ast
analyze: INFO: Importing function _Z12av_dict_copyPP12AVDictionaryPKS_i@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/dict.c.ast
analyze: INFO: Importing function _Z15av_buffer_unrefPP11AVBufferRef@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/buffer.c.ast
analyze: INFO: Importing function _Z15av_samples_copyPPhPKS_iiii14AVSampleFormat@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/samplefmt.c.ast
analyze: INFO: _Z29avfilter_graph_request_oldestP13AVFilterGraph@x86_64 has_work_wl block_exhausted no_block_aborted
analyze: INFO: Importing function _Z10av_malloczm@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/mem.c.ast
analyze: INFO: Importing function _Z9av_strdupPKc@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/mem.c.ast
analyze: INFO: _Z28avfilter_graph_queue_commandP13AVFilterGraphPKcS2_S2_id@x86_64 has_work_wl block_exhausted no_block_aborted
analyze: INFO: _Z27avfilter_graph_send_commandP13AVFilterGraphPKcS2_S2_Pcii@x86_64 has_work_wl block_exhausted no_block_aborted
analyze: INFO: Importing function _Z20ff_graph_thread_freeP13AVFilterGraph@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavfilter/pthread.c.ast
analyze: INFO: Importing function _Z13avfilter_freeP15AVFilterContext@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavfilter/avfilter.c.ast
analyze: INFO: Importing function _Z11av_opt_freePv@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/opt.c.ast
analyze: INFO: Importing function _Z12av_expr_freeP6AVExpr@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/eval.c.ast
analyze: INFO: _Z19avfilter_graph_freePP13AVFilterGraph@x86_64 has_work_wl not_exhausted no_block_aborted
analyze: INFO: Importing function _Z9av_callocmm@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/mem.c.ast
analyze: INFO: Importing function _Z21avfilter_config_linksP15AVFilterContext@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavfilter/avfilter.c.ast
analyze: INFO: Importing function _Z16ff_formats_unrefPP15AVFilterFormats@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavfilter/formats.c.ast
analyze: INFO: Importing function _Z24ff_channel_layouts_unrefPP22AVFilterChannelLayouts@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavfilter/formats.c.ast
analyze: INFO: _Z21avfilter_graph_configP13AVFilterGraphPv@x86_64 has_work_wl not_exhausted no_block_aborted
analyze: INFO: Importing function _Z24av_get_packed_sample_fmt14AVSampleFormat@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/samplefmt.c.ast
analyze: INFO: _ZL25find_best_sample_fmt_of_214AVSampleFormatS_S_@x86_64 empty_wl not_exhausted no_block_aborted
analyze: INFO: _ZL30swap_channel_layouts_on_filterP15AVFilterContext@x86_64 has_work_wl block_exhausted no_block_aborted
analyze: INFO: _ZL24reduce_formats_on_filterP15AVFilterContext@x86_64 has_work_wl block_exhausted no_block_aborted
analyze: INFO: Importing function _Z24ff_default_query_formatsP15AVFilterContext@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavfilter/formats.c.ast
analyze: INFO: Importing function _Z20av_pix_fmt_desc_nextPK18AVPixFmtDescriptor@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/pixdesc.c.ast
analyze: INFO: Importing function _Z22av_pix_fmt_desc_get_idPK18AVPixFmtDescriptor@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/pixdesc.c.ast
analyze: INFO: Importing function _Z16av_realloc_arrayPvmm@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/mem.c.ast
analyze: INFO: _ZL13query_formatsP13AVFilterGraphP7AVClass@x86_64 has_work_wl block_exhausted no_block_aborted
analyze: INFO: Importing function _Z9av_memdupPKvm@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/mem.c.ast
analyze: INFO: Importing function _Z16ff_merge_formatsP15AVFilterFormatsS0_11AVMediaType@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavfilter/formats.c.ast
analyze: INFO: Importing function _Z20ff_merge_sampleratesP15AVFilterFormatsS0_@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavfilter/formats.c.ast
analyze: INFO: _ZL17can_merge_formatsP15AVFilterFormatsS0_11AVMediaTypei@x86_64 empty_wl not_exhausted no_block_aborted
analyze: INFO: _ZL20filter_query_formatsP15AVFilterContext@x86_64 has_work_wl block_exhausted no_block_aborted
analyze: INFO: _Z31avfilter_graph_set_auto_convertP13AVFilterGraphj@x86_64 empty_wl not_exhausted no_block_aborted
analyze: INFO: Importing function _Z15ff_filter_allocPK8AVFilterPKc@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavfilter/avfilter.c.ast
analyze: INFO: Importing function _Z19av_opt_set_defaultsPv@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/opt.c.ast
analyze: INFO: Importing function _Z20av_opt_set_defaults2Pvii@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/opt.c.ast
analyze: INFO: Importing function _Z17avfilter_init_strP15AVFilterContextPKc@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavfilter/avfilter.c.ast
analyze: INFO: _Z28avfilter_graph_create_filterPP15AVFilterContextPK8AVFilterPKcS6_PvP13AVFilterGraph@x86_64 has_work_wl not_exhausted no_block_aborted
analyze: INFO: _Z25avfilter_graph_add_filterP13AVFilterGraphP15AVFilterContext@x86_64 empty_wl not_exhausted no_block_aborted
analyze: INFO: _Z25avfilter_graph_get_filterP13AVFilterGraphPKc@x86_64 empty_wl block_exhausted no_block_aborted
analyze: INFO: _Z20avfilter_graph_allocv@x86_64 has_work_wl not_exhausted no_block_aborted
analyze: INFO: /ssd/ednikru/ctu/tests/FFmpeg/libavfilter/avfiltergraph.c:118:9: warning: Use of memory after it is freed
analyze: INFO:         avfilter_free((*graph)->filters[0]);
analyze: INFO:         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
analyze: INFO: /ssd/ednikru/ctu/tests/FFmpeg/libavfilter/avfiltergraph.c:1318:31: warning: Access to field 'command' results in a dereference of a null pointer
analyze: INFO:             (*queue)->command = av_strdup(command);
analyze: INFO:             ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
analyze: INFO: /ssd/ednikru/ctu/tests/FFmpeg/libavfilter/formats.c:570:24: warning: Array access (via field 'inputs') results in a null pointer dereference
analyze: INFO: clang-4.0: /ssd/ednikru/ctu/llvm/tools/clang/lib/Frontend/TextDiagnostic.cpp:974: void highlightRange(const clang::CharSourceRange&, unsigned int, clang::FileID, const {anonymous}::SourceColumnMap&, std::string&, const clang::SourceManager&, const clang::LangOptions&): Assertion `StartColNo <= EndColNo && "Invalid range!"' failed.
analyze: INFO: #0 0x00007ff8a5be73f1 llvm::sys::PrintStackTrace(llvm::raw_ostream&) /ssd/ednikru/ctu/llvm/lib/Support/Unix/Signals.inc:402:0
analyze: INFO: #1 0x00007ff8a5be774c PrintStackTraceSignalHandler(void*) /ssd/ednikru/ctu/llvm/lib/Support/Unix/Signals.inc:466:0
analyze: INFO: #2 0x00007ff8a5be5912 llvm::sys::RunSignalHandlers() /ssd/ednikru/ctu/llvm/lib/Support/Signals.cpp:44:0
analyze: INFO: #3 0x00007ff8a5be6d83 SignalHandler(int) /ssd/ednikru/ctu/llvm/lib/Support/Unix/Signals.inc:256:0
analyze: INFO: #4 0x00007ff8a26b8cb0 (/lib/x86_64-linux-gnu/libc.so.6+0x36cb0)
analyze: INFO: #5 0x00007ff8a26b8c37 gsignal /build/eglibc-oGUzwX/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
analyze: INFO: #6 0x00007ff8a26bc028 abort /build/eglibc-oGUzwX/eglibc-2.19/stdlib/abort.c:91:0
analyze: INFO: #7 0x00007ff8a26b1bf6 __assert_fail_base /build/eglibc-oGUzwX/eglibc-2.19/assert/assert.c:92:0
analyze: INFO: #8 0x00007ff8a26b1ca2 (/lib/x86_64-linux-gnu/libc.so.6+0x2fca2)
analyze: INFO: #9 0x00007ff8a335d471 highlightRange(clang::CharSourceRange const&, unsigned int, clang::FileID, (anonymous namespace)::SourceColumnMap const&, std::string&, clang::SourceManager const&, clang::LangOptions const&) /ssd/ednikru/ctu/llvm/tools/clang/lib/Frontend/TextDiagnostic.cpp:977:0
analyze: INFO: #10 0x00007ff8a335e2fc clang::TextDiagnostic::emitSnippetAndCaret(clang::SourceLocation, clang::DiagnosticsEngine::Level, llvm::SmallVectorImpl<clang::CharSourceRange>&, llvm::ArrayRef<clang::FixItHint>, clang::SourceManager const&) /ssd/ednikru/ctu/llvm/tools/clang/lib/Frontend/TextDiagnostic.cpp:1155:0
analyze: INFO: #11 0x00007ff8a335f183 clang::TextDiagnostic::emitCodeContext(clang::SourceLocation, clang::DiagnosticsEngine::Level, llvm::SmallVectorImpl<clang::CharSourceRange>&, llvm::ArrayRef<clang::FixItHint>, clang::SourceManager const&) /ssd/ednikru/ctu/llvm/tools/clang/include/clang/Frontend/TextDiagnostic.h:96:0
analyze: INFO: #12 0x00007ff8a33049f8 clang::DiagnosticRenderer::emitCaret(clang::SourceLocation, clang::DiagnosticsEngine::Level, llvm::ArrayRef<clang::CharSourceRange>, llvm::ArrayRef<clang::FixItHint>, clang::SourceManager const&) /ssd/ednikru/ctu/llvm/tools/clang/lib/Frontend/DiagnosticRenderer.cpp:414:0
analyze: INFO: #13 0x00007ff8a3303855 clang::DiagnosticRenderer::emitDiagnostic(clang::SourceLocation, clang::DiagnosticsEngine::Level, llvm::StringRef, llvm::ArrayRef<clang::CharSourceRange>, llvm::ArrayRef<clang::FixItHint>, clang::SourceManager const*, llvm::PointerUnion<clang::Diagnostic const*, clang::StoredDiagnostic const*>) /ssd/ednikru/ctu/llvm/tools/clang/lib/Frontend/DiagnosticRenderer.cpp:127:0
analyze: INFO: #14 0x00007ff8a3362546 clang::TextDiagnosticPrinter::HandleDiagnostic(clang::DiagnosticsEngine::Level, clang::Diagnostic const&) /ssd/ednikru/ctu/llvm/tools/clang/lib/Frontend/TextDiagnosticPrinter.cpp:158:0
analyze: INFO: #15 0x00007ff8a4a89e3b clang::DiagnosticIDs::EmitDiag(clang::DiagnosticsEngine&, clang::DiagnosticIDs::Level) const /ssd/ednikru/ctu/llvm/tools/clang/lib/Basic/DiagnosticIDs.cpp:686:0
analyze: INFO: #16 0x00007ff8a4a89dbd clang::DiagnosticIDs::ProcessDiag(clang::DiagnosticsEngine&) const /ssd/ednikru/ctu/llvm/tools/clang/lib/Basic/DiagnosticIDs.cpp:678:0
analyze: INFO: #17 0x00007ff8a4a7fa5f clang::DiagnosticsEngine::ProcessDiag() /ssd/ednikru/ctu/llvm/tools/clang/include/clang/Basic/Diagnostic.h:809:0
analyze: INFO: #18 0x00007ff8a4a7c788 clang::DiagnosticsEngine::EmitCurrentDiagnostic(bool) /ssd/ednikru/ctu/llvm/tools/clang/lib/Basic/Diagnostic.cpp:384:0
analyze: INFO: #19 0x00007ff8977064b2 clang::DiagnosticBuilder::Emit() /ssd/ednikru/ctu/llvm/tools/clang/include/clang/Basic/Diagnostic.h:942:0
analyze: INFO: #20 0x00007ff8977064e0 clang::DiagnosticBuilder::~DiagnosticBuilder() /ssd/ednikru/ctu/llvm/tools/clang/include/clang/Basic/Diagnostic.h:966:0
analyze: INFO: #21 0x00007ff8976bab90 (anonymous namespace)::ClangDiagPathDiagConsumer::FlushDiagnosticsImpl(std::vector<clang::ento::PathDiagnostic const*, std::allocator<clang::ento::PathDiagnostic const*> >&, clang::ento::PathDiagnosticConsumer::FilesMade*) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:125:0
analyze: INFO: #22 0x00007ff895c1646a clang::ento::PathDiagnosticConsumer::FlushDiagnostics(clang::ento::PathDiagnosticConsumer::FilesMade*) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Core/PathDiagnostic.cpp:453:0
analyze: INFO: #23 0x00007ff895b02496 clang::ento::AnalysisManager::FlushDiagnostics() /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Core/AnalysisManager.cpp:53:0
analyze: INFO: #24 0x00007ff895b02328 clang::ento::AnalysisManager::~AnalysisManager() /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Core/AnalysisManager.cpp:45:0
analyze: INFO: #25 0x00007ff895b023fa clang::ento::AnalysisManager::~AnalysisManager() /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Core/AnalysisManager.cpp:49:0
analyze: INFO: #26 0x00007ff89772b204 std::default_delete<clang::ento::AnalysisManager>::operator()(clang::ento::AnalysisManager*) const /usr/include/c++/4.8/bits/unique_ptr.h:68:0
analyze: INFO: #27 0x00007ff89771d0f4 std::unique_ptr<clang::ento::AnalysisManager, std::default_delete<clang::ento::AnalysisManager> >::reset(clang::ento::AnalysisManager*) /usr/include/c++/4.8/bits/unique_ptr.h:263:0
analyze: INFO: #28 0x00007ff8976bd146 (anonymous namespace)::AnalysisConsumer::HandleTranslationUnit(clang::ASTContext&) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:668:0
analyze: INFO: #29 0x00007ff89a82565b clang::ParseAST(clang::Sema&, bool, bool) /ssd/ednikru/ctu/llvm/tools/clang/lib/Parse/ParseAST.cpp:161:0
analyze: INFO: #30 0x00007ff8a330ca16 clang::ASTFrontendAction::ExecuteAction() /ssd/ednikru/ctu/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:560:0
analyze: INFO: #31 0x00007ff8a330c4bb clang::FrontendAction::Execute() /ssd/ednikru/ctu/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:463:0
analyze: INFO: #32 0x00007ff8a32a18bf clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /ssd/ednikru/ctu/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp:954:0
analyze: INFO: #33 0x00007ff8a2dbe715 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /ssd/ednikru/ctu/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:249:0
analyze: INFO: #34 0x000000000044a081 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /ssd/ednikru/ctu/llvm/tools/clang/tools/driver/cc1_main.cpp:221:0
analyze: INFO: #35 0x000000000044043a ExecuteCC1Tool(llvm::ArrayRef<char const*>, llvm::StringRef) /ssd/ednikru/ctu/llvm/tools/clang/tools/driver/driver.cpp:299:0
analyze: INFO: #36 0x0000000000441038 main /ssd/ednikru/ctu/llvm/tools/clang/tools/driver/driver.cpp:380:0
analyze: INFO: #37 0x00007ff8a26a3f45 __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:321:0
analyze: INFO: #38 0x000000000043de99 _start (/ssd/ednikru/ctu/build_ctu_master/bin/clang-4.0+0x43de99)
analyze: INFO: Stack dump:
analyze: INFO: 0.	Program arguments: /ssd/ednikru/ctu/build_ctu_master/bin/clang-4.0 -cc1 -triple x86_64-unknown-linux-gnu -analyze -disable-free -main-file-name avfiltergraph.c -analyzer-store=region -analyzer-opt-analyze-nested-blocks -analyzer-eagerly-assume -analyzer-checker=core -analyzer-checker=apiModeling -analyzer-checker=unix -analyzer-checker=deadcode -analyzer-checker=security.insecureAPI.UncheckedReturn -analyzer-checker=security.insecureAPI.getpw -analyzer-checker=security.insecureAPI.gets -analyzer-checker=security.insecureAPI.mktemp -analyzer-checker=security.insecureAPI.mkstemp -analyzer-checker=security.insecureAPI.vfork -analyzer-checker=nullability.NullPassedToNonnull -analyzer-checker=nullability.NullReturnedFromNonnull -analyzer-output plist-multi-file -w -analyzer-config xtu-dir=/ssd/ednikru/ctu/tests/FFmpeg/.xtu -analyzer-config reanalyze-xtu-visited=true -analyzer-stats -mrelocation-model static -mthread-model posix -fno-signed-zeros -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -momit-leaf-frame-pointer -dwarf-column-info -debugger-tuning=gdb -resource-dir /ssd/ednikru/ctu/build_ctu_master/bin/../lib/clang/4.0.0 -I /ssd/ednikru/ctu/tests/FFmpeg -I /ssd/ednikru/ctu/tests/FFmpeg -I /usr/include/c++/4.8 -I /usr/include/x86_64-linux-gnu/c++/4.8 -I /usr/include/c++/4.8/backward -I /usr/local/include -I /usr/include/x86_64-linux-gnu -I /usr/include -D _ISOC99_SOURCE -D _FILE_OFFSET_BITS=64 -D _LARGEFILE_SOURCE -D _POSIX_C_SOURCE=200112 -D _XOPEN_SOURCE=600 -D ZLIB_CONST -D HAVE_AV_CONFIG_H -internal-isystem /usr/local/include -internal-isystem /ssd/ednikru/ctu/build_ctu_master/bin/../lib/clang/4.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -Wno-pointer-to-int-cast -Wno-parentheses -Wno-switch -Wno-format-zero-length -Wno-pointer-sign -Wno-maybe-uninitialized -std=c99 -fdebug-compilation-dir /home/ednikru/ssd/ctu/tests/FFmpeg -ferror-limit 19 -fmessage-length 0 -pthread -fobjc-runtime=gcc -fdiagnostics-show-option -vectorize-slp -o /ssd/ednikru/ctu/tests/FFmpeg/.xtu-out/report-emFLl8.plist -x c /ssd/ednikru/ctu/tests/FFmpeg/libavfilter/avfiltergraph.c
analyze: INFO: 1.	<eof> parser at end of file

**Comment by Xazax-hun** [comment]
Maybe one of the source ranges was not imported properly.

**Comment by gerazo** [comment]
also in curl/lib/conncache.c

**Comment by dkrupp** [comment]
Minimal example:
caller.c:
struct S{
  int a;
};
int f(struct S*);
void test(){    
    f(0);
}

lib.c:
#define MYMACRO(ctx) \
    ctx->a;
struct S{
  int a;
};

int f(struct S *ctx){  
  MYMACRO(ctx);
  return 0; 
}
