### ISSUE TITLE
astimporter assertion - calling getArgumentExpr() when arg is type

### ISSUE THREAD

**Issue by dkrupp** [dkrupp/clang#69]
cat ./.xtu-out/fails/matroskadec.c_20c47c24-4f4f-4433-b74e-78386c7752ba.out |grep "error:\|failed"
analyze: INFO: clang-4.0: /ssd/ednikru/ctu/llvm/tools/clang/include/clang/AST/Expr.h:2034: clang::Expr* clang::UnaryExprOrTypeTraitExpr::getArgumentExpr(): Assertion `!isArgumentType() && "calling getArgumentExpr() when arg is type"' failed.

ednikru@md-mtas2:~/ssd/ctu/tests/FFmpeg$ cat ./.xtu-out/fails/matroskadec.c_20c47c24-4f4f-4433-b74e-78386c7752ba.out
/ssd/ednikru/ctu/clang_github-fork/clang/tools/scan-build-py/bin/analyze-cc -I/ssd/ednikru/ctu/tests/FFmpeg -I/ssd/ednikru/ctu/tests/FFmpeg -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DZLIB_CONST -DHAVE_AV_CONFIG_H -std=c99 -fomit-frame-pointer -pthread -g -Wdeclaration-after-statement -Wall -Wdisabled-optimization -Wpointer-arith -Wredundant-decls -Wwrite-strings -Wtype-limits -Wundef -Wmissing-prototypes -Wno-pointer-to-int-cast -Wstrict-prototypes -Wempty-body -Wno-parentheses -Wno-switch -Wno-format-zero-length -Wno-pointer-sign -O3 -fno-math-errno -fno-signed-zeros -fno-tree-vectorize -Werror=format-security -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=return-type -Werror=vla -Wformat -Wno-maybe-uninitialized -MMD -MF libavformat/matroskadec.d -MT libavformat/matroskadec.o -c -o /ssd/ednikru/ctu/tests/FFmpeg/libavformat/matroskadec.o /ssd/ednikru/ctu/tests/FFmpeg/libavformat/matroskadec.c
analyze: INFO: execute compiler: gcc -I/ssd/ednikru/ctu/tests/FFmpeg -I/ssd/ednikru/ctu/tests/FFmpeg -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DZLIB_CONST -DHAVE_AV_CONFIG_H -std=c99 -fomit-frame-pointer -pthread -g -Wdeclaration-after-statement -Wall -Wdisabled-optimization -Wpointer-arith -Wredundant-decls -Wwrite-strings -Wtype-limits -Wundef -Wmissing-prototypes -Wno-pointer-to-int-cast -Wstrict-prototypes -Wempty-body -Wno-parentheses -Wno-switch -Wno-format-zero-length -Wno-pointer-sign -O3 -fno-math-errno -fno-signed-zeros -fno-tree-vectorize -Werror=format-security -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=return-type -Werror=vla -Wformat -Wno-maybe-uninitialized -MMD -MF libavformat/matroskadec.d -MT libavformat/matroskadec.o -c -o /ssd/ednikru/ctu/tests/FFmpeg/libavformat/matroskadec.o /ssd/ednikru/ctu/tests/FFmpeg/libavformat/matroskadec.c
analyze: INFO: clang-4.0: /ssd/ednikru/ctu/llvm/tools/clang/include/clang/AST/Expr.h:2034: clang::Expr* clang::UnaryExprOrTypeTraitExpr::getArgumentExpr(): Assertion `!isArgumentType() && "calling getArgumentExpr() when arg is type"' failed.
analyze: INFO: #0 0x00007fcc4dd2a3f1 llvm::sys::PrintStackTrace(llvm::raw_ostream&) /ssd/ednikru/ctu/llvm/lib/Support/Unix/Signals.inc:402:0
analyze: INFO: #1 0x00007fcc4dd2a74c PrintStackTraceSignalHandler(void*) /ssd/ednikru/ctu/llvm/lib/Support/Unix/Signals.inc:466:0
analyze: INFO: #2 0x00007fcc4dd28912 llvm::sys::RunSignalHandlers() /ssd/ednikru/ctu/llvm/lib/Support/Signals.cpp:44:0
analyze: INFO: #3 0x00007fcc4dd29d83 SignalHandler(int) /ssd/ednikru/ctu/llvm/lib/Support/Unix/Signals.inc:256:0
analyze: INFO: #4 0x00007fcc4a7fbcb0 (/lib/x86_64-linux-gnu/libc.so.6+0x36cb0)
analyze: INFO: #5 0x00007fcc4a7fbc37 gsignal /build/eglibc-oGUzwX/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
analyze: INFO: #6 0x00007fcc4a7ff028 abort /build/eglibc-oGUzwX/eglibc-2.19/stdlib/abort.c:91:0
analyze: INFO: #7 0x00007fcc4a7f4bf6 __assert_fail_base /build/eglibc-oGUzwX/eglibc-2.19/assert/assert.c:92:0
analyze: INFO: #8 0x00007fcc4a7f4ca2 (/lib/x86_64-linux-gnu/libc.so.6+0x2fca2)
analyze: INFO: #9 0x00007fcc3e2cd40f clang::UnaryExprOrTypeTraitExpr::getArgumentExpr() /ssd/ednikru/ctu/llvm/tools/clang/include/clang/AST/Expr.h:2035:0
analyze: INFO: #10 0x00007fcc3e2cd432 clang::UnaryExprOrTypeTraitExpr::getArgumentExpr() const /ssd/ednikru/ctu/llvm/tools/clang/include/clang/AST/Expr.h:2039:0
analyze: INFO: #11 0x00007fcc3e2c898a (anonymous namespace)::WalkAST::isSizeof(clang::Expr const*, clang::Expr const*) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Checkers/CStringSyntaxChecker.cpp:51:0
analyze: INFO: #12 0x00007fcc3e2c8d83 (anonymous namespace)::WalkAST::containsBadStrncatPattern(clang::CallExpr const*) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Checkers/CStringSyntaxChecker.cpp:126:0
analyze: INFO: #13 0x00007fcc3e2c8e71 (anonymous namespace)::WalkAST::VisitCallExpr(clang::CallExpr*) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Checkers/CStringSyntaxChecker.cpp:141:0
analyze: INFO: #14 0x00007fcc3e2c9d01 clang::StmtVisitorBase<clang::make_ptr, (anonymous namespace)::WalkAST, void>::Visit(clang::Stmt*) /ssd/ednikru/ctu/build_ctu_master/tools/clang/include/clang/AST/StmtNodes.inc:329:0
analyze: INFO: #15 0x00007fcc3e2c9273 (anonymous namespace)::WalkAST::VisitChildren(clang::Stmt*) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Checkers/CStringSyntaxChecker.cpp:171:0
analyze: INFO: #16 0x00007fcc3e2c8bf9 (anonymous namespace)::WalkAST::VisitStmt(clang::Stmt*) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Checkers/CStringSyntaxChecker.cpp:92:0
analyze: INFO: #17 0x00007fcc3e2cc50b clang::StmtVisitorBase<clang::make_ptr, (anonymous namespace)::WalkAST, void>::VisitIfStmt(clang::IfStmt*) /ssd/ednikru/ctu/build_ctu_master/tools/clang/include/clang/AST/StmtNodes.inc:843:0
analyze: INFO: #18 0x00007fcc3e2ca451 clang::StmtVisitorBase<clang::make_ptr, (anonymous namespace)::WalkAST, void>::Visit(clang::Stmt*) /ssd/ednikru/ctu/build_ctu_master/tools/clang/include/clang/AST/StmtNodes.inc:843:0
analyze: INFO: #19 0x00007fcc3e2c9273 (anonymous namespace)::WalkAST::VisitChildren(clang::Stmt*) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Checkers/CStringSyntaxChecker.cpp:171:0
analyze: INFO: #20 0x00007fcc3e2c8bf9 (anonymous namespace)::WalkAST::VisitStmt(clang::Stmt*) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Checkers/CStringSyntaxChecker.cpp:92:0
analyze: INFO: #21 0x00007fcc3e2cb3c1 clang::StmtVisitorBase<clang::make_ptr, (anonymous namespace)::WalkAST, void>::VisitCompoundStmt(clang::CompoundStmt*) /ssd/ednikru/ctu/build_ctu_master/tools/clang/include/clang/AST/StmtNodes.inc:79:0
analyze: INFO: #22 0x00007fcc3e2c9947 clang::StmtVisitorBase<clang::make_ptr, (anonymous namespace)::WalkAST, void>::Visit(clang::Stmt*) /ssd/ednikru/ctu/build_ctu_master/tools/clang/include/clang/AST/StmtNodes.inc:79:0
analyze: INFO: #23 0x00007fcc3e2c9273 (anonymous namespace)::WalkAST::VisitChildren(clang::Stmt*) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Checkers/CStringSyntaxChecker.cpp:171:0
analyze: INFO: #24 0x00007fcc3e2c8bf9 (anonymous namespace)::WalkAST::VisitStmt(clang::Stmt*) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Checkers/CStringSyntaxChecker.cpp:92:0
analyze: INFO: #25 0x00007fcc3e2cc4bf clang::StmtVisitorBase<clang::make_ptr, (anonymous namespace)::WalkAST, void>::VisitForStmt(clang::ForStmt*) /ssd/ednikru/ctu/build_ctu_master/tools/clang/include/clang/AST/StmtNodes.inc:831:0
analyze: INFO: #26 0x00007fcc3e2ca421 clang::StmtVisitorBase<clang::make_ptr, (anonymous namespace)::WalkAST, void>::Visit(clang::Stmt*) /ssd/ednikru/ctu/build_ctu_master/tools/clang/include/clang/AST/StmtNodes.inc:831:0
analyze: INFO: #27 0x00007fcc3e2c9273 (anonymous namespace)::WalkAST::VisitChildren(clang::Stmt*) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Checkers/CStringSyntaxChecker.cpp:171:0
analyze: INFO: #28 0x00007fcc3e2c8bf9 (anonymous namespace)::WalkAST::VisitStmt(clang::Stmt*) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Checkers/CStringSyntaxChecker.cpp:92:0
analyze: INFO: #29 0x00007fcc3e2cb3c1 clang::StmtVisitorBase<clang::make_ptr, (anonymous namespace)::WalkAST, void>::VisitCompoundStmt(clang::CompoundStmt*) /ssd/ednikru/ctu/build_ctu_master/tools/clang/include/clang/AST/StmtNodes.inc:79:0
analyze: INFO: #30 0x00007fcc3e2c9947 clang::StmtVisitorBase<clang::make_ptr, (anonymous namespace)::WalkAST, void>::Visit(clang::Stmt*) /ssd/ednikru/ctu/build_ctu_master/tools/clang/include/clang/AST/StmtNodes.inc:79:0
analyze: INFO: #31 0x00007fcc3e2c9303 (anonymous namespace)::CStringSyntaxChecker::checkASTCodeBody(clang::Decl const*, clang::ento::AnalysisManager&, clang::ento::BugReporter&) const /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Checkers/CStringSyntaxChecker.cpp:184:0
analyze: INFO: #32 0x00007fcc3e2cd1b0 void clang::ento::check::ASTCodeBody::_checkBody<(anonymous namespace)::CStringSyntaxChecker>(void*, clang::Decl const*, clang::ento::AnalysisManager&, clang::ento::BugReporter&) /ssd/ednikru/ctu/llvm/tools/clang/include/clang/StaticAnalyzer/Core/Checker.h:53:0
analyze: INFO: #33 0x00007fcc3dccd9ed clang::ento::CheckerFn<void (clang::Decl const*, clang::ento::AnalysisManager&, clang::ento::BugReporter&)>::operator()(clang::Decl const*, clang::ento::AnalysisManager&, clang::ento::BugReporter&) const /ssd/ednikru/ctu/llvm/tools/clang/include/clang/StaticAnalyzer/Core/CheckerManager.h:60:0
analyze: INFO: #34 0x00007fcc3dcc7ca7 clang::ento::CheckerManager::runCheckersOnASTBody(clang::Decl const*, clang::ento::AnalysisManager&, clang::ento::BugReporter&) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Core/CheckerManager.cpp:85:0
analyze: INFO: #35 0x00007fcc3f800ca5 (anonymous namespace)::AnalysisConsumer::HandleCode(clang::Decl*, unsigned int, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*> >*) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:790:0
analyze: INFO: #36 0x00007fcc3f7feaf1 (anonymous namespace)::AnalysisConsumer::VisitFunctionDecl(clang::FunctionDecl*) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:363:0
analyze: INFO: #37 0x00007fcc3f80f826 clang::RecursiveASTVisitor<(anonymous namespace)::AnalysisConsumer>::WalkUpFromFunctionDecl(clang::FunctionDecl*) /ssd/ednikru/ctu/build_ctu_master/tools/clang/include/clang/AST/DeclNodes.inc:389:0
analyze: INFO: #38 0x00007fcc3f8077ef clang::RecursiveASTVisitor<(anonymous namespace)::AnalysisConsumer>::TraverseFunctionDecl(clang::FunctionDecl*) /ssd/ednikru/ctu/llvm/tools/clang/include/clang/AST/RecursiveASTVisitor.h:1928:0
analyze: INFO: #39 0x00007fcc3f802711 clang::RecursiveASTVisitor<(anonymous namespace)::AnalysisConsumer>::TraverseDecl(clang::Decl*) /ssd/ednikru/ctu/build_ctu_master/tools/clang/include/clang/AST/DeclNodes.inc:389:0
analyze: INFO: #40 0x00007fcc3f800078 (anonymous namespace)::AnalysisConsumer::HandleTranslationUnit(clang::ASTContext&) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:649:0
analyze: INFO: #41 0x00007fcc4296865b clang::ParseAST(clang::Sema&, bool, bool) /ssd/ednikru/ctu/llvm/tools/clang/lib/Parse/ParseAST.cpp:161:0
analyze: INFO: #42 0x00007fcc4b44fa16 clang::ASTFrontendAction::ExecuteAction() /ssd/ednikru/ctu/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:560:0
analyze: INFO: #43 0x00007fcc4b44f4bb clang::FrontendAction::Execute() /ssd/ednikru/ctu/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:463:0
analyze: INFO: #44 0x00007fcc4b3e48bf clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /ssd/ednikru/ctu/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp:954:0
analyze: INFO: #45 0x00007fcc4af01715 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /ssd/ednikru/ctu/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:249:0
analyze: INFO: #46 0x000000000044a081 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /ssd/ednikru/ctu/llvm/tools/clang/tools/driver/cc1_main.cpp:221:0
analyze: INFO: #47 0x000000000044043a ExecuteCC1Tool(llvm::ArrayRef<char const*>, llvm::StringRef) /ssd/ednikru/ctu/llvm/tools/clang/tools/driver/driver.cpp:299:0
analyze: INFO: #48 0x0000000000441038 main /ssd/ednikru/ctu/llvm/tools/clang/tools/driver/driver.cpp:380:0
analyze: INFO: #49 0x00007fcc4a7e6f45 __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:321:0
analyze: INFO: #50 0x000000000043de99 _start (/ssd/ednikru/ctu/build_ctu_master/bin/clang-4.0+0x43de99)
analyze: INFO: Stack dump:
analyze: INFO: 0.	Program arguments: /ssd/ednikru/ctu/build_ctu_master/bin/clang-4.0 -cc1 -triple x86_64-unknown-linux-gnu -analyze -disable-free -main-file-name matroskadec.c -analyzer-store=region -analyzer-opt-analyze-nested-blocks -analyzer-eagerly-assume -analyzer-checker=core -analyzer-checker=apiModeling -analyzer-checker=unix -analyzer-checker=deadcode -analyzer-checker=security.insecureAPI.UncheckedReturn -analyzer-checker=security.insecureAPI.getpw -analyzer-checker=security.insecureAPI.gets -analyzer-checker=security.insecureAPI.mktemp -analyzer-checker=security.insecureAPI.mkstemp -analyzer-checker=security.insecureAPI.vfork -analyzer-checker=nullability.NullPassedToNonnull -analyzer-checker=nullability.NullReturnedFromNonnull -analyzer-output plist-multi-file -w -analyzer-config xtu-dir=/ssd/ednikru/ctu/tests/FFmpeg/.xtu -analyzer-config reanalyze-xtu-visited=true -analyzer-stats -mrelocation-model static -mthread-model posix -fno-signed-zeros -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -momit-leaf-frame-pointer -dwarf-column-info -debugger-tuning=gdb -resource-dir /ssd/ednikru/ctu/build_ctu_master/bin/../lib/clang/4.0.0 -I /ssd/ednikru/ctu/tests/FFmpeg -I /ssd/ednikru/ctu/tests/FFmpeg -I /usr/include/c++/4.8 -I /usr/include/x86_64-linux-gnu/c++/4.8 -I /usr/include/c++/4.8/backward -I /usr/local/include -I /usr/include/x86_64-linux-gnu -I /usr/include -D _ISOC99_SOURCE -D _FILE_OFFSET_BITS=64 -D _LARGEFILE_SOURCE -D _POSIX_C_SOURCE=200112 -D _XOPEN_SOURCE=600 -D ZLIB_CONST -D HAVE_AV_CONFIG_H -internal-isystem /usr/local/include -internal-isystem /ssd/ednikru/ctu/build_ctu_master/bin/../lib/clang/4.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -Wno-pointer-to-int-cast -Wno-parentheses -Wno-switch -Wno-format-zero-length -Wno-pointer-sign -Wno-maybe-uninitialized -std=c99 -fdebug-compilation-dir /home/ednikru/ssd/ctu/tests/FFmpeg -ferror-limit 19 -fmessage-length 0 -pthread -fobjc-runtime=gcc -fdiagnostics-show-option -vectorize-slp -o /ssd/ednikru/ctu/tests/FFmpeg/.xtu-out/report-igrJmS.plist -x c /ssd/ednikru/ctu/tests/FFmpeg/libavformat/matroskadec.c
analyze: INFO: 1.	<eof> parser at end of file

**Comment by Xazax-hun** [comment]
This is an issue in the CStringChecker and not in the ASTImporter.

**Comment by Xazax-hun** [comment]
Fix is proposed: https://reviews.llvm.org/D29384

**Comment by Xazax-hun** [comment]
Fixed in master: https://github.com/llvm-mirror/clang/commit/caac6f64e30f4b9b5fc8e9637259e357d0805d26
