### ISSUE TITLE
astcontext assertion - analyze:  Assertion `ToDecl->hasBody()' failed.

### ISSUE THREAD

**Issue by dkrupp** [dkrupp/clang#70]
ffmpeg 

ednikru@md-mtas2:~/ssd/ctu/tests/FFmpeg$ cat ./.xtu-out/fails/msmpeg4dec.c_d90dbbdd-becc-4c5a-b646-0e15b7633b21.out |grep "error:\|failed"
analyze: INFO: clang-4.0: /ssd/ednikru/ctu/llvm/tools/clang/lib/AST/ASTContext.cpp:1558: const clang::FunctionDecl* clang::ASTContext::getXTUDefinition(const clang::FunctionDecl*, clang::CompilerInstance&, llvm::StringRef, clang::DiagnosticsEngine&, std::function<clang::ASTUnit*(llvm::StringRef)>): Assertion `ToDecl->hasBody()' failed.

ednikru@md-mtas2:~/ssd/ctu/tests/FFmpeg$ cat ./.xtu-out/fails/msmpeg4dec.c_d90dbbdd-becc-4c5a-b646-0e15b7633b21.out
/ssd/ednikru/ctu/clang_github-fork/clang/tools/scan-build-py/bin/analyze-cc -I/ssd/ednikru/ctu/tests/FFmpeg -I/ssd/ednikru/ctu/tests/FFmpeg -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DZLIB_CONST -DHAVE_AV_CONFIG_H -std=c99 -fomit-frame-pointer -pthread -g -Wdeclaration-after-statement -Wall -Wdisabled-optimization -Wpointer-arith -Wredundant-decls -Wwrite-strings -Wtype-limits -Wundef -Wmissing-prototypes -Wno-pointer-to-int-cast -Wstrict-prototypes -Wempty-body -Wno-parentheses -Wno-switch -Wno-format-zero-length -Wno-pointer-sign -O3 -fno-math-errno -fno-signed-zeros -fno-tree-vectorize -Werror=format-security -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=return-type -Werror=vla -Wformat -Wno-maybe-uninitialized -MMD -MF libavcodec/msmpeg4dec.d -MT libavcodec/msmpeg4dec.o -c -o /ssd/ednikru/ctu/tests/FFmpeg/libavcodec/msmpeg4dec.o /ssd/ednikru/ctu/tests/FFmpeg/libavcodec/msmpeg4dec.c
analyze: INFO: execute compiler: gcc -I/ssd/ednikru/ctu/tests/FFmpeg -I/ssd/ednikru/ctu/tests/FFmpeg -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DZLIB_CONST -DHAVE_AV_CONFIG_H -std=c99 -fomit-frame-pointer -pthread -g -Wdeclaration-after-statement -Wall -Wdisabled-optimization -Wpointer-arith -Wredundant-decls -Wwrite-strings -Wtype-limits -Wundef -Wmissing-prototypes -Wno-pointer-to-int-cast -Wstrict-prototypes -Wempty-body -Wno-parentheses -Wno-switch -Wno-format-zero-length -Wno-pointer-sign -O3 -fno-math-errno -fno-signed-zeros -fno-tree-vectorize -Werror=format-security -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=return-type -Werror=vla -Wformat -Wno-maybe-uninitialized -MMD -MF libavcodec/msmpeg4dec.d -MT libavcodec/msmpeg4dec.o -c -o /ssd/ednikru/ctu/tests/FFmpeg/libavcodec/msmpeg4dec.o /ssd/ednikru/ctu/tests/FFmpeg/libavcodec/msmpeg4dec.c
analyze: INFO: Importing function _Z27ff_msmpeg4_coded_block_predP14MpegEncContextiPPh@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavcodec/msmpeg4.c.ast
analyze: INFO: Importing function _Z6av_logPviPKcz@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavutil/log.c.ast
analyze: INFO: Importing function _Z19ff_h263_pred_motionP14MpegEncContextiiPiS1_@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavcodec/h263.c.ast
analyze: INFO: _ZL20msmpeg4v34_decode_mbP14MpegEncContextPA64_s@x86_64 has_work_wl block_exhausted no_block_aborted
analyze: INFO: _ZL20msmpeg4v12_decode_mbP14MpegEncContextPA64_s@x86_64 empty_wl block_exhausted no_block_aborted
analyze: INFO: _Z23ff_msmpeg4_decode_blockP14MpegEncContextPsiiPKh@x86_64 has_work_wl block_exhausted no_block_aborted
analyze: INFO: Importing function _Z18ff_msmpeg4_pred_dcP14MpegEncContextiPPsPi@x86_64 from /ssd/ednikru/ctu/tests/FFmpeg/.xtu//ast/x86_64/ssd/ednikru/ctu/tests/FFmpeg/libavcodec/msmpeg4.c.ast
analyze: INFO: clang-4.0: /ssd/ednikru/ctu/llvm/tools/clang/lib/AST/ASTContext.cpp:1558: const clang::FunctionDecl* clang::ASTContext::getXTUDefinition(const clang::FunctionDecl*, clang::CompilerInstance&, llvm::StringRef, clang::DiagnosticsEngine&, std::function<clang::ASTUnit*(llvm::StringRef)>): Assertion `ToDecl->hasBody()' failed.
analyze: INFO: #0 0x00007f5a7658e3f1 llvm::sys::PrintStackTrace(llvm::raw_ostream&) /ssd/ednikru/ctu/llvm/lib/Support/Unix/Signals.inc:402:0
analyze: INFO: #1 0x00007f5a7658e74c PrintStackTraceSignalHandler(void*) /ssd/ednikru/ctu/llvm/lib/Support/Unix/Signals.inc:466:0
analyze: INFO: #2 0x00007f5a7658c912 llvm::sys::RunSignalHandlers() /ssd/ednikru/ctu/llvm/lib/Support/Signals.cpp:44:0
analyze: INFO: #3 0x00007f5a7658dd83 SignalHandler(int) /ssd/ednikru/ctu/llvm/lib/Support/Unix/Signals.inc:256:0
analyze: INFO: #4 0x00007f5a7305fcb0 (/lib/x86_64-linux-gnu/libc.so.6+0x36cb0)
analyze: INFO: #5 0x00007f5a7305fc37 gsignal /build/eglibc-oGUzwX/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
analyze: INFO: #6 0x00007f5a73063028 abort /build/eglibc-oGUzwX/eglibc-2.19/stdlib/abort.c:91:0
analyze: INFO: #7 0x00007f5a73058bf6 __assert_fail_base /build/eglibc-oGUzwX/eglibc-2.19/assert/assert.c:92:0
analyze: INFO: #8 0x00007f5a73058ca2 (/lib/x86_64-linux-gnu/libc.so.6+0x2fca2)
analyze: INFO: #9 0x00007f5a6d08e38e clang::ASTContext::getXTUDefinition(clang::FunctionDecl const*, clang::CompilerInstance&, llvm::StringRef, clang::DiagnosticsEngine&, std::function<clang::ASTUnit* (llvm::StringRef)>) /ssd/ednikru/ctu/llvm/tools/clang/lib/AST/ASTContext.cpp:1559:0
analyze: INFO: #10 0x00007f5a66517fbf clang::ento::AnyFunctionCall::getRuntimeDefinition() const /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Core/CallEvent.cpp:394:0
analyze: INFO: #11 0x00007f5a66599fe4 clang::ento::ExprEngine::defaultEvalCall(clang::ento::NodeBuilder&, clang::ento::ExplodedNode*, clang::ento::CallEvent const&) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngineCallAndReturn.cpp:912:0
analyze: INFO: #12 0x00007f5a6652d84b clang::ento::CheckerManager::runCheckersForEvalCall(clang::ento::ExplodedNodeSet&, clang::ento::ExplodedNodeSet const&, clang::ento::CallEvent const&, clang::ento::ExprEngine&) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Core/CheckerManager.cpp:617:0
analyze: INFO: #13 0x00007f5a66598b80 clang::ento::ExprEngine::evalCall(clang::ento::ExplodedNodeSet&, clang::ento::ExplodedNode*, clang::ento::CallEvent const&) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngineCallAndReturn.cpp:519:0
analyze: INFO: #14 0x00007f5a66598a1d clang::ento::ExprEngine::VisitCallExpr(clang::CallExpr const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngineCallAndReturn.cpp:485:0
analyze: INFO: #15 0x00007f5a665639ac clang::ento::ExprEngine::Visit(clang::Stmt const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:1179:0
analyze: INFO: #16 0x00007f5a665605ee clang::ento::ExprEngine::ProcessStmt(clang::CFGStmt, clang::ento::ExplodedNode*) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:507:0
analyze: INFO: #17 0x00007f5a6655f8ee clang::ento::ExprEngine::processCFGElement(clang::CFGElement, clang::ento::ExplodedNode*, unsigned int, clang::ento::NodeBuilderContext*) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:355:0
analyze: INFO: #18 0x00007f5a66548eb5 clang::ento::CoreEngine::HandlePostStmt(clang::CFGBlock const*, unsigned int, clang::ento::ExplodedNode*) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp:532:0
analyze: INFO: #19 0x00007f5a66547d28 clang::ento::CoreEngine::dispatchWorkItem(clang::ento::ExplodedNode*, clang::ProgramPoint, clang::ento::WorkListUnit const&) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp:279:0
analyze: INFO: #20 0x00007f5a66547908 clang::ento::CoreEngine::ExecuteWorkList(clang::LocationContext const*, unsigned int, llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp:216:0
analyze: INFO: #21 0x00007f5a680bd2e8 clang::ento::ExprEngine::ExecuteWorkList(clang::LocationContext const*, unsigned int) /ssd/ednikru/ctu/llvm/tools/clang/include/clang/StaticAnalyzer/Core/PathSensitive/ExprEngine.h:110:0
analyze: INFO: #22 0x00007f5a68064f40 (anonymous namespace)::AnalysisConsumer::ActionExprEngine(clang::Decl*, bool, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*> >*) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:826:0
analyze: INFO: #23 0x00007f5a68065330 (anonymous namespace)::AnalysisConsumer::RunPathSensitiveChecks(clang::Decl*, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*> >*) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:862:0
analyze: INFO: #24 0x00007f5a68064d06 (anonymous namespace)::AnalysisConsumer::HandleCode(clang::Decl*, unsigned int, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*> >*) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:792:0
analyze: INFO: #25 0x00007f5a68063695 (anonymous namespace)::AnalysisConsumer::HandleDeclsCallGraph(unsigned int) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:575:0
analyze: INFO: #26 0x00007f5a680640c5 (anonymous namespace)::AnalysisConsumer::HandleTranslationUnit(clang::ASTContext&) /ssd/ednikru/ctu/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:657:0
analyze: INFO: #27 0x00007f5a6b1cc65b clang::ParseAST(clang::Sema&, bool, bool) /ssd/ednikru/ctu/llvm/tools/clang/lib/Parse/ParseAST.cpp:161:0
analyze: INFO: #28 0x00007f5a73cb3a16 clang::ASTFrontendAction::ExecuteAction() /ssd/ednikru/ctu/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:560:0
analyze: INFO: #29 0x00007f5a73cb34bb clang::FrontendAction::Execute() /ssd/ednikru/ctu/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:463:0
analyze: INFO: #30 0x00007f5a73c488bf clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /ssd/ednikru/ctu/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp:954:0
analyze: INFO: #31 0x00007f5a73765715 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /ssd/ednikru/ctu/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:249:0
analyze: INFO: #32 0x000000000044a081 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /ssd/ednikru/ctu/llvm/tools/clang/tools/driver/cc1_main.cpp:221:0
analyze: INFO: #33 0x000000000044043a ExecuteCC1Tool(llvm::ArrayRef<char const*>, llvm::StringRef) /ssd/ednikru/ctu/llvm/tools/clang/tools/driver/driver.cpp:299:0
analyze: INFO: #34 0x0000000000441038 main /ssd/ednikru/ctu/llvm/tools/clang/tools/driver/driver.cpp:380:0
analyze: INFO: #35 0x00007f5a7304af45 __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:321:0
analyze: INFO: #36 0x000000000043de99 _start (/ssd/ednikru/ctu/build_ctu_master/bin/clang-4.0+0x43de99)
analyze: INFO: Stack dump:
analyze: INFO: 0.	Program arguments: /ssd/ednikru/ctu/build_ctu_master/bin/clang-4.0 -cc1 -triple x86_64-unknown-linux-gnu -analyze -disable-free -main-file-name msmpeg4dec.c -analyzer-store=region -analyzer-opt-analyze-nested-blocks -analyzer-eagerly-assume -analyzer-checker=core -analyzer-checker=apiModeling -analyzer-checker=unix -analyzer-checker=deadcode -analyzer-checker=security.insecureAPI.UncheckedReturn -analyzer-checker=security.insecureAPI.getpw -analyzer-checker=security.insecureAPI.gets -analyzer-checker=security.insecureAPI.mktemp -analyzer-checker=security.insecureAPI.mkstemp -analyzer-checker=security.insecureAPI.vfork -analyzer-checker=nullability.NullPassedToNonnull -analyzer-checker=nullability.NullReturnedFromNonnull -analyzer-output plist-multi-file -w -analyzer-config xtu-dir=/ssd/ednikru/ctu/tests/FFmpeg/.xtu -analyzer-config reanalyze-xtu-visited=true -analyzer-stats -mrelocation-model static -mthread-model posix -fno-signed-zeros -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -momit-leaf-frame-pointer -dwarf-column-info -debugger-tuning=gdb -resource-dir /ssd/ednikru/ctu/build_ctu_master/bin/../lib/clang/4.0.0 -I /ssd/ednikru/ctu/tests/FFmpeg -I /ssd/ednikru/ctu/tests/FFmpeg -I /usr/include/c++/4.8 -I /usr/include/x86_64-linux-gnu/c++/4.8 -I /usr/include/c++/4.8/backward -I /usr/local/include -I /usr/include/x86_64-linux-gnu -I /usr/include -D _ISOC99_SOURCE -D _FILE_OFFSET_BITS=64 -D _LARGEFILE_SOURCE -D _POSIX_C_SOURCE=200112 -D _XOPEN_SOURCE=600 -D ZLIB_CONST -D HAVE_AV_CONFIG_H -internal-isystem /usr/local/include -internal-isystem /ssd/ednikru/ctu/build_ctu_master/bin/../lib/clang/4.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -Wno-pointer-to-int-cast -Wno-parentheses -Wno-switch -Wno-format-zero-length -Wno-pointer-sign -Wno-maybe-uninitialized -std=c99 -fdebug-compilation-dir /home/ednikru/ssd/ctu/tests/FFmpeg -ferror-limit 19 -fmessage-length 0 -pthread -fobjc-runtime=gcc -fdiagnostics-show-option -vectorize-slp -o /ssd/ednikru/ctu/tests/FFmpeg/.xtu-out/report-1NIBiU.plist -x c /ssd/ednikru/ctu/tests/FFmpeg/libavcodec/msmpeg4dec.c
analyze: INFO: 1.	<eof> parser at end of file
analyze: INFO: 2.	While analyzing stack:
analyze: INFO: 	#0 static int msmpeg4_decode_dc(MpegEncContext *s, int n, int *dir_ptr)
analyze: INFO: 3.	/ssd/ednikru/ctu/tests/FFmpeg/libavcodec/msmpeg4dec.c:627:18: Error evaluating statement
analyze: INFO: 4.	/ssd/ednikru/ctu/tests/FFmpeg/libavcodec/msmpeg4dec.c:627:18: Error evaluating statement

**Comment by Xazax-hun** [comment]
This is probably the result of a node that is not yet supported by the ASTImporter, not a faulty import.

**Comment by gerazo** [comment]
also in also in curl/lib/conncache.c

**Comment by gerazo** [comment]
ASTImporter cannot import any functions which contain asm snippets. The simplest call to a function containing one line asm fails.

**Comment by gerazo** [comment]
example:
lib.cpp:

int getkey() {
  int res;
  asm ( "mov $42, %0"
      : "=r" (res));
  return res;
}

main.cpp:

int main() {
  printf("key to all everything: %d\n", getkey());
  return 0;
}

**Comment by dkrupp** [comment]
add asserts to ASTImporter wherever it could return null_ptr at importring function declaration and remove assert from astcontext.cpp

**Comment by gerazo** [comment]
Fixed by: https://github.com/dkrupp/clang/pull/94
