### ISSUE TITLE
Add peak and average peak memory usage to the statistics html.

### ISSUE THREAD

**Issue by Xazax-hun** [dkrupp/clang#99]

**Comment by dkrupp** [comment]
I started to do this but could not finish when left for holiday. I will add this to the statistics on monday (20th of march)

**Comment by dkrupp** [comment]
peak memory usage is added.

why average is important?

**Comment by Xazax-hun** [comment]
Usually we run the analyzer in multiple processes. Maybe saying that the overall memory usage will be 2.5 times more is not fair only based on the peak.

**Comment by dkrupp** [comment]
then we should add the sum of the peak usages for a project as "total memory usage" of the analysis
